version: '3.8'  # Specify the version

services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      - POSTGRES_USER=aniket
      - POSTGRES_PASSWORD=aniket
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  mongo:
    container_name: ms_mongo_db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aniket
      - MONGO_INITDB_ROOT_PASSWORD=aniket
    volumes:
      - mongo:/data/db  # Changed mount point to /data/db
    ports:
      - "27017:27017"
    networks:
      - microservices-net

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aniket
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aniket
      - ME_CONFIG_MONGODB_SERVER=mongo

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservices-net

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgmail.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE='false'
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
